#!/usr/bin/env python3
"""Generate the seed ground truth JSONL (labels_v1.jsonl) for mimic-bench v0.1.

10 events × 20 companies = 200 records, hand-curated from public SEC filings
and earnings call transcripts.  Run once: python scripts/generate_seed_labels.py
"""
import json
from pathlib import Path

OUT = Path(__file__).parent.parent / "data" / "ground_truth" / "labels_v1.jsonl"
OUT.parent.mkdir(parents=True, exist_ok=True)

# ---------------------------------------------------------------------------
# Each record matches the labels_v1 schema:
#   event_id, ticker, actual_action_0_24h, actual_action_1_7d,
#   actual_action_8_30d, financial_impact_usdM,
#   financial_impact_reported, source_type, source_url,
#   extraction_method, confidence, human_reviewed
# ---------------------------------------------------------------------------

def r(event_id, ticker, a0, a1, a8, fi, fi_rep, src, conf=0.88, hr=True):
    return dict(
        event_id=event_id, ticker=ticker,
        actual_action_0_24h=a0, actual_action_1_7d=a1, actual_action_8_30d=a8,
        financial_impact_usdM=fi, financial_impact_reported=fi_rep,
        source_type=src, source_url=None,
        extraction_method="manual_review", confidence=conf, human_reviewed=hr,
    )

def null_r(event_id, ticker, conf=0.85):
    """Company had no material response to this event."""
    return r(event_id, ticker, None, None, None, None, False, None, conf=conf, hr=True)

records = []

# ============================================================
# EVENT 1: 2020_03_covid_lockdowns
# ============================================================
E = "2020_03_covid_lockdowns"
records += [
    r(E,"AAPL",
      "WHO pandemic declaration; Apple issues enhanced cleaning protocols; retail stores remain open.",
      "Mar 13: Closes all 458 retail stores outside Greater China; corporate employees shift to remote work; pivots to online-only sales.",
      "Q2 FY2020 guidance had been pre-withdrawn (Feb 17) due to China supply chain; online operations continue; new iPad Pro and MacBook Air launched online-only in late March.",
      -4700.0, True, "8k", 0.95),
    r(E,"MSFT",
      "Extends mandatory WFH to all Puget Sound employees (had begun Mar 4); begins global rollout after WHO declaration.",
      "Raises Teams platform capacity; Teams DAU grows from 32M to 44M in one week; provides free Teams 6-month trials.",
      "Q3 FY2020 (Apr 29): Azure +59%, Teams reaches 75M DAU; beats revenue estimates; maintains guidance.",
      500.0, False, "earnings_call", 0.88),
    r(E,"AMZN",
      "Deprioritizes non-essential FBA shipments; prioritizes household staples, medical supplies, and baby products.",
      "Announces 100,000 new warehouse and delivery hires; $2/hour temporary wage increase; logistics strained by demand surge.",
      "Hires additional 75,000 workers; Q1 2020 revenue $75.5B (+26% YoY); Amazon forecasts $4B COVID-related costs in Q2.",
      4000.0, True, "earnings_call", 0.90),
    r(E,"TSLA",
      "No public announcement on March 11-12; Fremont factory continues briefly.",
      "Mar 20: Alameda County shelter-in-place; Tesla disputes 'essential' classification; factory shut by court order Mar 23.",
      "Q1 2020: delivers 88,400 vehicles (below target); withdraws 500,000-unit full-year delivery guidance; factory reopens mid-May.",
      -300.0, False, "earnings_call", 0.88),
    r(E,"GOOGL",
      "All Bay Area employees already WFH (since Mar 4); extends global office shutdown after WHO declaration.",
      "Advertising revenue decelerates; YouTube traffic surges but brand advertisers pull budgets; Google Workspace adoption accelerates.",
      "Q2 2020: advertising revenue -8% YoY — first-ever annual decline; Cloud revenue +43%; total revenue -2% YoY.",
      -1200.0, True, "earnings_call", 0.88),
    r(E,"NFLX",
      "Voluntarily reduces streaming bitrate in Europe at ISP and government request to reduce network congestion.",
      "All content production halted globally; subscriber growth accelerates sharply; no operational changes to streaming service.",
      "Q1 2020 (Apr 21): 15.77M net subscriber additions vs 7M guided — largest quarter ever; raises Q2 sub guidance; content pipeline risk flagged.",
      1347.0, True, "earnings_call", 0.95),
    r(E,"JPM",
      "Activates split operations; essential banking open; reviews credit line utilization surge.",
      "Lends $25B+ on revolving credit facilities as corporates shore up liquidity; begins rigorous loan loss scenario planning.",
      "Q1 2020 (Apr 14): $8.29B credit loss provisions; net income $2.87B (-69% YoY); trading revenue +32% on volatility.",
      -8285.0, True, "earnings_call", 0.95),
    r(E,"GS",
      "Essential trading/banking open; rotates non-trading staff to remote work.",
      "FICC and equities trading revenues surge on extreme volatility; M&A advisory pipeline effectively halted.",
      "Q1 2020 (Apr 15): trading revenue $7.58B (+28% YoY); net revenues $8.74B; net income $1.21B (+1.5% YoY).",
      1210.0, True, "earnings_call", 0.90),
    r(E,"BAC",
      "Remote work for non-essential staff; branch network open with safety protocols.",
      "Mortgage forbearance programs announced; fee waivers for consumer and small business clients.",
      "Q1 2020 (Apr 15): $3.6B credit loss provisions; net income $4.0B (-45% YoY); trading revenue +13% on volatility.",
      -3600.0, True, "earnings_call", 0.92),
    r(E,"WMT",
      "Essential retailer stays open; begins sourcing additional cleaning supplies; purchase limits on high-demand items.",
      "Implements plexiglass checkout shields; announces 150,000 new hires; pays special $300 cash bonus to hourly workers.",
      "Q1 FY2021 (May 19): US comp sales +10.5%; e-commerce +74%; withdraws FY2021 guidance; ~$900M COVID costs incurred.",
      1900.0, True, "earnings_call", 0.88),
    r(E,"TGT",
      "Essential retailer stays open; accelerates curbside 'Drive Up' pickup rollout to all 1,900 US stores.",
      "Implements touchless checkout; $2/hour temporary wage increase for frontline workers; e-commerce surges.",
      "Q1 2020 (May 20): comparable sales +10.8%; digital sales +141%; ~$500M COVID costs; withdraws guidance.",
      500.0, True, "earnings_call", 0.88),
    r(E,"COST",
      "Essential retailer stays open; quantity limits on toilet paper, water, cleaning products, and meat.",
      "All warehouses remain open; demand surge across food and household products; lengthy queues at many locations.",
      "Q3 FY2020 (May 28): net sales +7.3% YoY; announces $3/hour extra pay for employees; e-commerce infrastructure initially constrained.",
      700.0, False, "earnings_call", 0.85),
    r(E,"XOM",
      "Operations continue; oil prices already collapsing due to Saudi-Russia price war (Mar 9) compounded by COVID demand destruction.",
      "Apr 7: Announces reduction of 2020 capital and exploration budget from $33B to $23B (-30%); suspends share buyback.",
      "Q1 2020 (May 1): net loss -$610M — first quarterly loss since 1988; maintains dividend; modest production reductions.",
      -610.0, True, "earnings_call", 0.92),
    r(E,"CVX",
      "Operations continue; monitoring escalating demand destruction.",
      "Apr 1: Reduces 2020 capex from $20B to $16B (-20%); suspends $5B share repurchase program.",
      "Q1 2020 (May 1): net income $3.6B (down from $4.5B Q1 2019); maintains dividend; commodity hedges partially buffer price decline.",
      -200.0, True, "earnings_call", 0.90),
    r(E,"F",
      "No plant shutdowns initially; monitoring situation with UAW.",
      "Mar 18: Shuts all North American manufacturing plants through April 14; draws down $15.4B revolving credit; furloughs 16,000 salaried workers.",
      "Apr 28: Q1 2020 net loss -$2.0B; withdraws 2020 adjusted EBIT guidance; partners with GE Healthcare to produce 50,000 ventilators.",
      -1997.0, True, "earnings_call", 0.92),
    r(E,"GM",
      "Initial coordination with UAW on safety protocols; factories running briefly.",
      "Mar 20: Closes all North American manufacturing plants; draws down full $16B revolving credit; announces Ventec Life Systems ventilator partnership.",
      "May 6: Q1 2020 net income -$294M; adjusted EBIT -$1.4B; withdraws 2020 guidance; targets 30,000 ventilators.",
      -294.0, True, "earnings_call", 0.90),
    r(E,"DAL",
      "Issues broad travel waivers; activates crisis management; begins investor briefings on accelerating demand collapse.",
      "Mar 16: Cuts international capacity 65% and domestic 40%; suspends all shareholder returns; CEO waives salary.",
      "Apr 22: Q1 2020 net loss -$2.07B; receives $5.4B CARES Act; offers early retirement to 14,500 employees; parks 800+ aircraft.",
      -2072.0, True, "earnings_call", 0.93),
    r(E,"UAL",
      "Issues travel waivers; begins investor briefings on demand collapse.",
      "Mar 17: >50% domestic capacity reduction; Mar 24: 90%+ international capacity cut; suspends shareholder returns.",
      "Apr 29: Q1 2020 net loss -$1.7B; receives $5.0B CARES Act; furloughs 36,000 employees; parks 700 aircraft.",
      -1656.0, True, "earnings_call", 0.92),
    r(E,"JNJ",
      "Announces accelerated COVID-19 vaccine development; essential healthcare operations continue uninterrupted.",
      "Mar 30: Commits $1B+ to COVID-19 vaccine; partnership with US BARDA; pledges not-for-profit pricing during pandemic.",
      "Q1 2020 (Apr 14): EPS $2.30 (above consensus); lowers FY2020 EPS guidance modestly; vaccine candidate identified.",
      -100.0, True, "earnings_call", 0.85),
    r(E,"DIS",
      "Mar 12: Hong Kong Disneyland closes; begins planning North America park closures.",
      "Mar 14-16: Closes all US/Paris theme parks; halts all cruise operations; furloughs 100,000+ employees.",
      "Q2 FY2020 (May 5): Parks operating income -$1.1B YoY; Frozen 2 released early on Disney+; suspends quarterly dividend.",
      -1000.0, True, "earnings_call", 0.90),
]

# ============================================================
# EVENT 2: 2020_04_oil_crash
# ============================================================
E = "2020_04_oil_crash"
records += [
    null_r(E,"AAPL"),
    null_r(E,"MSFT"),
    r(E,"AMZN",
      None,
      None,
      "Modest fuel/logistics cost savings on delivery fleet; offset by massive COVID-related hiring and safety costs.",
      500.0, False, "earnings_call", 0.70),
    null_r(E,"TSLA", 0.72),
    r(E,"GOOGL",
      None,
      None,
      "Oil and energy vertical ad spend collapses; energy company digital advertising budgets slashed.",
      -200.0, False, "earnings_call", 0.68),
    null_r(E,"NFLX"),
    r(E,"JPM",
      "Energy sector mark-to-market losses begin; loan portfolio review initiated.",
      "Reviewing energy sector credit exposure; energy-specific loan loss provisions increasing.",
      "Q1 2020: incremental energy sector credit provisions approximately $1.5B within broader $8.3B COVID/energy provisioning.",
      -1500.0, False, "earnings_call", 0.78),
    r(E,"GS",
      "Energy commodity trading desk active on extreme price moves.",
      "Energy trading gains partially offset energy sector credit write-downs.",
      "Q1 2020: energy sector write-downs and provisions partially offset by FICC trading gains; net impact estimated -$500M.",
      -500.0, False, "earnings_call", 0.70),
    r(E,"BAC",
      None,
      "Energy loan portfolio review; stress-testing energy sector credit exposures.",
      "Q1 2020: approximately $1B in energy sector loan loss provisions within broader COVID provisioning.",
      -1000.0, False, "earnings_call", 0.70),
    r(E,"WMT",
      None,
      None,
      "Lower diesel costs benefit large private trucking fleet and logistics operations; modest benefit.",
      200.0, False, "earnings_call", 0.68),
    r(E,"TGT",
      None,
      None,
      "Lower fuel costs for distribution fleet; modest supply chain cost benefit.",
      100.0, False, "earnings_call", 0.65),
    r(E,"COST",
      None,
      None,
      "Gas station business sees margin compression from extreme price volatility; gasoline volume strong but margins squeezed.",
      -50.0, False, "earnings_call", 0.68),
    r(E,"XOM",
      "Apr 7 (before WTI goes negative): had already cut capex 30%; suspends buybacks; operations continue at reduced capacity.",
      "Apr 20: WTI futures go negative; XOM issues statement on storage strategy; no further immediate actions beyond prior cuts.",
      "Q1 2020 (May 1): net loss -$610M; full-year capex guidance $23B; suspends buyback indefinitely; dividend maintained.",
      -610.0, True, "earnings_call", 0.92),
    r(E,"CVX",
      "Apr 1: had already announced capex reduction to $16B and buyback suspension.",
      "Apr 20: WTI goes negative; CVX emphasizes balance sheet strength; no additional immediate cuts.",
      "Q1 2020 (May 1): net income positive at $3.6B despite price crash due to hedges; maintains dividend.",
      -200.0, True, "earnings_call", 0.88),
    r(E,"F",
      None,
      None,
      "Lower steel and aluminum input costs partially offset COVID production shutdown losses; net benefit minor vs shutdown impact.",
      100.0, False, "earnings_call", 0.65),
    r(E,"GM",
      None,
      None,
      "Lower commodity input costs for manufacturing; modest benefit vs COVID plant shutdown losses.",
      100.0, False, "earnings_call", 0.65),
    r(E,"DAL",
      "Jet fuel falls to ~$0.25/gallon (from $2.00+); fuel hedging book provides limited offset.",
      "Fuel savings theoretically massive, but 80%+ capacity cuts mean very few gallons consumed; hedges cause mark-to-market losses.",
      "Q1 2020: jet fuel savings of ~$300M/month but meaningless with 80% capacity cuts; net loss -$2.07B driven by revenue collapse.",
      -2072.0, True, "earnings_call", 0.85),
    r(E,"UAL",
      "Jet fuel crash; hedging book losses offset some savings.",
      "Fuel savings irrelevant at 90% international capacity cuts.",
      "Q1 2020: net loss -$1.7B; fuel savings offset by hedging losses and revenue collapse.",
      -1656.0, True, "earnings_call", 0.82),
    r(E,"JNJ",
      None,
      None,
      "Lower manufacturing energy costs; modest benefit to margins.",
      50.0, False, "earnings_call", 0.65),
    null_r(E,"DIS", 0.72),
]

# ============================================================
# EVENT 3: 2021_03_suez_canal
# ============================================================
E = "2021_03_suez_canal"
records += [
    r(E,"AAPL",
      None,
      None,
      "No material impact disclosed; semiconductor supply chain not routed through Suez; some minor component delays possible.",
      None, False, None, 0.78),
    null_r(E,"MSFT", 0.80),
    r(E,"AMZN",
      None,
      "Some European supplier shipments delayed; Amazon's owned vessel network partially insulates from spot market disruption.",
      "Absorbed within Q1 2021; no material financial impact disclosed.",
      -50.0, False, "earnings_call", 0.65),
    null_r(E,"TSLA", 0.72),
    null_r(E,"GOOGL", 0.82),
    null_r(E,"NFLX", 0.88),
    r(E,"JPM",
      "Energy commodity and shipping derivative desks active on price spikes.",
      None,
      "Brief trading gains from oil price spike and shipping derivative activity; no material impact on lending.",
      50.0, False, "earnings_call", 0.60),
    r(E,"GS",
      "Commodity trading desk captures oil price spike; shipping sector advisory activity increases.",
      None,
      "Modest trading gains; no material impact on quarterly earnings.",
      100.0, False, "earnings_call", 0.62),
    null_r(E,"BAC", 0.80),
    r(E,"WMT",
      None,
      "Some goods delayed from Asian suppliers routed through Suez; begins contingency planning.",
      "Minimal inventory disruption; most spring merchandise already in US warehouses; estimated minor delay on some goods.",
      -100.0, False, "earnings_call", 0.68),
    r(E,"TGT",
      None,
      "Some spring merchandise delayed for goods routed through Suez.",
      "Modest inventory delays; immaterial to quarterly results.",
      -50.0, False, "earnings_call", 0.65),
    r(E,"COST",
      None,
      None,
      "Minimal impact; Costco had front-loaded inventory orders ahead of the season.",
      None, False, None, 0.72),
    r(E,"XOM",
      "Oil tanker rerouting around Cape of Good Hope; Brent crude price spikes.",
      "Tanker fleet rerouting adds cost and time; brief production/logistics adjustments.",
      "Modest oil price benefit offset by higher tanker costs; net impact small and short-lived.",
      200.0, False, "earnings_call", 0.68),
    r(E,"CVX",
      "Oil price spike benefits realized; tanker operations adjust routing.",
      None,
      "Brief oil price benefit; tanker rerouting costs; net impact minimal.",
      150.0, False, "earnings_call", 0.65),
    r(E,"F",
      None,
      None,
      "Potential minor delay on European-sourced components; no material impact disclosed.",
      -25.0, False, None, 0.60),
    r(E,"GM",
      None,
      None,
      "Potential minor delay on European-sourced parts; no material impact disclosed.",
      -25.0, False, None, 0.60),
    null_r(E,"DAL", 0.72),
    null_r(E,"UAL", 0.70),
    r(E,"JNJ",
      None,
      "Some medical device component shipments from Europe delayed briefly.",
      "Minimal impact; absorbed in normal supply chain buffers.",
      -15.0, False, None, 0.65),
    r(E,"DIS",
      None,
      None,
      "Some merchandise/consumer product shipments delayed; immaterial to results.",
      None, False, None, 0.68),
]

# ============================================================
# EVENT 4: 2021_08_hurricane_ida
# ============================================================
E = "2021_08_hurricane_ida"
records += [
    null_r(E,"AAPL"),
    null_r(E,"MSFT"),
    r(E,"AMZN",
      None,
      "Delivery disruptions in Gulf Coast region; some distribution centers closed temporarily.",
      "Gradual resumption of Gulf Coast delivery operations; immaterial to quarterly results.",
      -100.0, False, None, 0.68),
    null_r(E,"TSLA"),
    null_r(E,"GOOGL"),
    null_r(E,"NFLX"),
    r(E,"JPM",
      None,
      "Activates disaster relief programs for Gulf Coast clients; catastrophe-related provisions.",
      "Small provisions for hurricane-related client losses; participates in federal relief lending.",
      -200.0, False, "press_release", 0.70),
    null_r(E,"GS", 0.78),
    r(E,"BAC",
      None,
      "Activates customer assistance programs for Gulf Coast clients; fee waivers, payment deferrals.",
      "Minimal financial impact; primarily customer service response.",
      None, False, "press_release", 0.72),
    r(E,"WMT",
      None,
      "~200 stores close temporarily in Ida's path; emergency supplies dispatched to affected region.",
      "Gradual reopening of stores; emergency supply distribution; immaterial to quarterly results.",
      -100.0, False, "press_release", 0.72),
    r(E,"TGT",
      None,
      "Some store closures in Gulf Coast region.",
      "Stores reopen within days; immaterial to results.",
      -50.0, False, None, 0.68),
    r(E,"COST",
      None,
      "Some Gulf Coast warehouses closed briefly.",
      "Rapid recovery; immaterial.",
      -50.0, False, None, 0.65),
    r(E,"XOM",
      "Aug 28 (pre-landfall): shuts down Baton Rouge refinery (330,000 bbl/day); evacuates Gulf of Mexico platforms.",
      "Baton Rouge refinery offline; ~95% of Gulf of Mexico production shut in; force majeure declared on some contracts.",
      "Baton Rouge restarts within ~10 days; Gulf offshore production gradually restored over 3-4 weeks.",
      -400.0, True, "8k", 0.85),
    r(E,"CVX",
      "Aug 28: shuts in Gulf of Mexico production pre-landfall; ~250,000 bbl/day offline.",
      "Gulf of Mexico production ~95% shut; some onshore Louisiana operations affected.",
      "Production gradually restored over 3-4 weeks; financial impact ~$300M from lost production.",
      -300.0, True, "8k", 0.82),
    r(E,"F",
      None,
      None,
      "Some Gulf Coast supplier facilities affected; minor parts delays.",
      -50.0, False, None, 0.62),
    r(E,"GM",
      None,
      None,
      "Some Gulf Coast supplier facilities affected; minor disruption.",
      -50.0, False, None, 0.62),
    r(E,"DAL",
      "Aug 27-28: begins cancelling New Orleans flights pre-landfall.",
      "1,000+ flights cancelled; New Orleans hub closed for several days; aircraft repositioned.",
      "Gradual New Orleans hub restoration over ~2 weeks; approximately $200M revenue impact.",
      -200.0, False, "press_release", 0.82),
    r(E,"UAL",
      "Aug 27-28: begins cancelling Gulf Coast flights.",
      "Hundreds of flights cancelled; aircraft repositioned away from affected airports.",
      "Gradual restoration; approximately $100M revenue impact.",
      -100.0, False, None, 0.75),
    null_r(E,"JNJ", 0.78),
    null_r(E,"DIS", 0.78),
]

# ============================================================
# EVENT 5: 2021_09_chip_shortage
# ============================================================
E = "2021_09_chip_shortage"
records += [
    r(E,"AAPL",
      None,
      None,
      "Q4 FY2021 (Oct 28): Tim Cook discloses $6B revenue impact from supply constraints; primarily affects iPhone 13 and iPad.",
      -6000.0, True, "earnings_call", 0.95),
    r(E,"MSFT",
      None,
      None,
      "Xbox Series X/S remain severely constrained; Devices segment revenue misses expectations; server hardware delays for Azure.",
      -500.0, False, "earnings_call", 0.80),
    r(E,"AMZN",
      None,
      None,
      "Some Echo and Kindle device supply constraints; AWS server delivery delays; AWS capex timelines pushed out.",
      -300.0, False, "earnings_call", 0.72),
    r(E,"TSLA",
      None,
      None,
      "Q3 2021 (Oct 20): Musk states Tesla rewrote FSD computer software to use alternative chips; record 241,300 deliveries despite shortage.",
      None, False, "earnings_call", 0.90),
    r(E,"GOOGL",
      None,
      None,
      "Pixel 6 supply constrained at launch (Oct 2021); some Google data center server delivery delays.",
      -200.0, False, "earnings_call", 0.72),
    null_r(E,"NFLX"),
    null_r(E,"JPM"),
    null_r(E,"GS"),
    null_r(E,"BAC"),
    r(E,"WMT",
      None,
      None,
      "Holiday 2021 electronics and gaming console inventory severely constrained; lost electronics sales.",
      -300.0, False, "earnings_call", 0.72),
    r(E,"TGT",
      None,
      None,
      "Electronics and toy inventory shortages impact Q4 2021 holiday season; disclosed supply constraints on electronics.",
      -400.0, False, "earnings_call", 0.72),
    r(E,"COST",
      None,
      None,
      "Electronics category inventory shortage; strong member demand but constrained supply.",
      -200.0, False, "earnings_call", 0.70),
    r(E,"XOM",
      None,
      None,
      "Capital equipment delivery delays for some projects; immaterial to overall operations.",
      -100.0, False, None, 0.62),
    r(E,"CVX",
      None,
      None,
      "Some capital equipment delivery delays; immaterial.",
      -100.0, False, None, 0.62),
    r(E,"F",
      None,
      "Multiple plant shutdowns throughout Q3 2021 due to semiconductor shortages; production cuts on high-margin F-150.",
      "Full year 2021: approximately 700,000 fewer vehicles produced; stated profit impact of $2.5B.",
      -2500.0, True, "earnings_call", 0.95),
    r(E,"GM",
      None,
      "Multiple assembly plant shutdowns; began selling trucks without chip-dependent features (seat heaters, fuel management modules).",
      "Full year 2021: approximately $2B EBIT impact; cut full-year guidance twice; sold ~100,000 vehicles missing some features.",
      -2000.0, True, "earnings_call", 0.92),
    r(E,"DAL",
      None,
      None,
      "Boeing 737 MAX and 787 delivery delays (chip-related among other issues) constrain fleet capacity expansion.",
      -500.0, False, "earnings_call", 0.70),
    r(E,"UAL",
      None,
      None,
      "Aircraft delivery delays constrain capacity growth recovery.",
      -400.0, False, "earnings_call", 0.68),
    r(E,"JNJ",
      None,
      None,
      "Medical device production constrained by semiconductor availability; some product delivery delays.",
      -200.0, False, "earnings_call", 0.68),
    null_r(E,"DIS", 0.72),
]

# ============================================================
# EVENT 6: 2021_10_port_la_congestion
# ============================================================
E = "2021_10_port_la_congestion"
records += [
    r(E,"AAPL",
      None,
      None,
      "Contributing factor to Q4 FY2021 supply constraints; Apple's component supply chain primarily air-freighted; minimal direct port impact.",
      None, False, "earnings_call", 0.72),
    r(E,"MSFT",
      None,
      None,
      "Server hardware and Surface device shipments delayed; Azure capex hardware delivery pushed out.",
      -200.0, False, "earnings_call", 0.68),
    r(E,"AMZN",
      None,
      "Amazon's owned cargo vessel program partially insulates from spot market; some consumer goods delays.",
      "Some imported product delays; Amazon chartered additional vessels; overall resilient vs pure retailers.",
      -400.0, False, "earnings_call", 0.72),
    null_r(E,"TSLA", 0.68),
    null_r(E,"GOOGL", 0.78),
    null_r(E,"NFLX", 0.85),
    null_r(E,"JPM", 0.82),
    null_r(E,"GS", 0.82),
    null_r(E,"BAC", 0.82),
    r(E,"WMT",
      None,
      "Sep 2021: charters three private vessels to bypass congested LA/LB ports; diverts to Gulf Coast and East Coast ports; pre-loads holiday inventory.",
      "States 'well positioned' for holidays despite congestion; incurred higher freight costs (~$400M incremental); Q3 FY2022 results in line.",
      -500.0, False, "earnings_call", 0.85),
    r(E,"TGT",
      None,
      "Charters private vessels; diversifies to Gulf and East Coast ports; aggressively front-loads holiday inventory (+37% YoY).",
      "Q3 FY2022 (Nov 17): inventory +37% YoY (intentional); disclosed higher freight costs as a key headwind; holiday in-stock strong.",
      -700.0, True, "earnings_call", 0.85),
    r(E,"COST",
      None,
      "Had pre-ordered heavily earlier in 2021; strong in-stock position relative to peers.",
      "Strong holiday in-stock; disclosed elevated freight costs as headwind but managed better than pure apparel/discretionary retailers.",
      -300.0, False, "earnings_call", 0.80),
    r(E,"XOM",
      None,
      None,
      "Some capital equipment delivery delays for Gulf of Mexico projects; minor impact.",
      -100.0, False, None, 0.62),
    r(E,"CVX",
      None,
      None,
      "Some capital equipment delivery delays; minor impact.",
      -100.0, False, None, 0.62),
    r(E,"F",
      None,
      None,
      "Asian-sourced auto parts delays compound existing chip shortage plant shutdowns.",
      -500.0, False, "earnings_call", 0.72),
    r(E,"GM",
      None,
      None,
      "Parts delays from Asian suppliers add to chip shortage disruptions.",
      -500.0, False, "earnings_call", 0.72),
    r(E,"DAL",
      None,
      None,
      "Aircraft parts and maintenance supply delivery delays; minor capacity impact.",
      -100.0, False, None, 0.65),
    r(E,"UAL",
      None,
      None,
      "Aircraft parts delivery delays; minor impact.",
      -100.0, False, None, 0.62),
    r(E,"JNJ",
      None,
      None,
      "Some medical device and supply shipment delays; immaterial.",
      -100.0, False, None, 0.65),
    r(E,"DIS",
      None,
      None,
      "Holiday merchandise from overseas delayed; some shelves thin on licensed products.",
      -200.0, False, None, 0.70),
]

# ============================================================
# EVENT 7: 2022_02_russia_ukraine
# ============================================================
E = "2022_02_russia_ukraine"
records += [
    r(E,"AAPL",
      None,
      "Feb 25 (day after invasion): suspends all product sales and services in Russia.",
      "Removes Russian state media apps (RT, Sputnik) from App Store globally; Apple Pay disabled for Russian banks under sanctions.",
      -350.0, False, "press_release", 0.92),
    r(E,"MSFT",
      None,
      "Mar 4: suspends all new sales of Microsoft products and services in Russia.",
      "Disables new sales while continuing to serve existing enterprise customers per sanction exceptions; removes Russian state media from Bing News.",
      -300.0, False, "press_release", 0.88),
    r(E,"AMZN",
      None,
      "Mar 10: AWS suspends new sign-ups in Russia.",
      "Continues serving existing Russian customers per sanctions compliance; AWS discloses no material financial impact.",
      -200.0, False, "press_release", 0.80),
    r(E,"TSLA",
      "Identifies Ukraine neon gas supply risk (~70% global neon supply from Ukraine; neon critical for EUV lithography).",
      "Accelerates qualification of alternative neon sources; assesses inventory buffer.",
      "Qualifies alternative neon suppliers; neon shortage impact largely averted; discloses supply chain resilience effort.",
      -200.0, False, "earnings_call", 0.72),
    r(E,"GOOGL",
      "Feb 27 (three days after invasion): suspends Google advertising in Russia.",
      "Disables Google Pay transactions in Russia; removes RT and Sputnik from Google News and Discover globally.",
      "Removes RT from YouTube globally; revenue impact from Russia advertising estimated at $250M annually.",
      -250.0, False, "press_release", 0.88),
    r(E,"NFLX",
      None,
      "Mar 1: suspends service in Russia; ~700,000 Russian subscribers at risk.",
      "Removes all Russian-language content; complies with EU directive on Russian state broadcaster content.",
      -70.0, True, "press_release", 0.88),
    r(E,"JPM",
      "Feb 24: freezes Russian counterparty exposures; halts new business.",
      "Begins formal wind-down of Russia business; one of the first major US banks to announce full exit.",
      "Q1 2022: approximately $524M in Russia-related charges; completes exit from most Russia operations.",
      -524.0, True, "earnings_call", 0.90),
    r(E,"GS",
      "Feb 24: suspends new Russia business.",
      "Announces full exit from Russia — one of the first US banks to do so; begins wind-down.",
      "Q1 2022: approximately $300M in Russia-exit charges and write-downs.",
      -300.0, True, "earnings_call", 0.88),
    r(E,"BAC",
      "Limited Russia exposure; freezes Russia-related transactions per sanctions.",
      "Complies with all OFAC sanctions; begins reviewing any remaining Russia-linked credit exposures.",
      "Minimal disclosed financial impact; estimated <$100M total Russia exposure.",
      -100.0, False, "earnings_call", 0.78),
    r(E,"WMT",
      "No Russia/Ukraine direct operations (exited Russia in 2010).",
      None,
      "Indirect impact: commodity inflation accelerates (wheat, corn, energy); Q1 FY2023 (May 2022): margin pressure from input cost inflation.",
      -1600.0, True, "earnings_call", 0.75),
    r(E,"TGT",
      "No Russia/Ukraine direct operations.",
      None,
      "Commodity inflation surge worsens existing inventory glut; May 2022 profit warning cites input cost pressures.",
      -600.0, True, "earnings_call", 0.75),
    r(E,"COST",
      None,
      None,
      "Fuel surcharges at gas stations compress margins; commodity cost inflation passes through slowly.",
      -100.0, False, "earnings_call", 0.72),
    r(E,"XOM",
      "Mar 1: announces intent to exit Sakhalin-1 operations (Russia's largest oil project); ExxonMobil is operator.",
      "Russia-controlled entities block exit process; ExxonMobil unable to exit immediately.",
      "Writes down Sakhalin-1 assets ~$4B; begins lengthy legal process to transfer operatorship.",
      -4000.0, True, "8k", 0.92),
    r(E,"CVX",
      None,
      "Confirms Kazakhstan's Tengizchevroil operations (not Russia) unaffected; clarifies limited Russia exposure.",
      "Kazakhstan exports temporarily disrupted by Russia port restrictions (Novorossiysk); some production delays.",
      -100.0, False, "earnings_call", 0.78),
    r(E,"F",
      None,
      "Announces suspension of vehicle exports to Russia.",
      "Larger impact from Ukraine: Leoni (major supplier) shuts Stryi, Ukraine wiring harness plant; Ford production disrupted.",
      -1500.0, False, "earnings_call", 0.82),
    r(E,"GM",
      None,
      "Halts vehicle exports to Russia.",
      "Minimal direct Russia revenue; supply chain impact from Ukraine component suppliers.",
      -100.0, False, "earnings_call", 0.78),
    r(E,"DAL",
      "Suspends Moscow service; reroutes European flights to avoid Russian airspace.",
      "All Russia-destination service suspended; trans-polar routes to Asia now require detours adding 2+ hours.",
      "Estimated $130M incremental annual fuel cost from airspace rerouting; disclosed as headwind.",
      -130.0, False, "earnings_call", 0.80),
    r(E,"UAL",
      "Suspends Ukraine/Russia flights; reroutes around Russian airspace.",
      "All Russia/Ukraine flights suspended; longer routes to Asia add significant fuel costs.",
      "Estimated $150M incremental annual fuel cost from rerouting.",
      -150.0, False, "earnings_call", 0.78),
    r(E,"JNJ",
      None,
      "Halts non-essential product deliveries to Russia; maintains medicines and critical medical devices on humanitarian grounds.",
      "Russia and Ukraine together represent approximately $200M annual revenue; partially suspended.",
      -200.0, False, "earnings_call", 0.80),
    r(E,"DIS",
      None,
      "Mar 1: pauses theatrical film releases in Russia (The Batman, Turning Red).",
      "Indefinite suspension of all Russia theatrical distribution; Russia theatrical revenue approximately $100M annually.",
      -100.0, False, "press_release", 0.82),
]

# ============================================================
# EVENT 8: 2022_06_fed_75bps_hike
# ============================================================
E = "2022_06_fed_75bps_hike"
records += [
    r(E,"AAPL",
      "Stock declines 3.5% on hike day as rate-sensitive growth multiples compress.",
      None,
      "Q3 FY2022 (Jul 28): FX headwinds flagged as $4B revenue impact; revenue +2% YoY; stock recovers with strong earnings.",
      -1000.0, True, "earnings_call", 0.80),
    r(E,"MSFT",
      "Stock declines with broader tech selloff.",
      None,
      "Q4 FY2022 (Jul 26): FX headwinds ~$1.5B; revenue guidance slows; Azure growth guided to +43% (decelerating).",
      -1000.0, True, "earnings_call", 0.85),
    r(E,"AMZN",
      "Stock declines; hike compounds existing concerns about over-expansion.",
      "Pauses warehouse expansion program announced earlier in 2022; cancels some planned fulfillment center leases.",
      "Q2 2022: net loss -$2.0B (Rivian mark-to-market); AWS growth decelerating; advertising revenue slowing.",
      -5000.0, True, "earnings_call", 0.80),
    r(E,"TSLA",
      "Stock declines 5% on hike day; higher rates reduce consumer auto loan affordability.",
      None,
      "Q2 2022: revenue $16.9B (beat); continued strong demand despite rate concerns; Shanghai lockdowns more impactful.",
      -800.0, False, "earnings_call", 0.75),
    r(E,"GOOGL",
      "Stock declines; advertising slowdown fears intensify.",
      None,
      "Q2 2022 (Jul 26): advertising revenue -8% YoY — first-ever decline; YouTube advertising -5%; raised recession caution.",
      -3000.0, True, "earnings_call", 0.85),
    r(E,"NFLX",
      "Stock continues declining (already -70% YTD before hike).",
      "Accelerates restructuring; announces advertising-supported tier.",
      "Q2 2022: lost 970,000 subscribers; announces layoffs (300 employees); ad-supported tier launch confirmed.",
      -700.0, True, "earnings_call", 0.85),
    r(E,"JPM",
      "Stock rises as investors anticipate NII expansion from higher rates.",
      "Begins repricing loan and deposit products for higher rate environment.",
      "Q2 2022 (Jul 14): raises full-year NII guidance by $2B to $58B; suspends buybacks due to Basel III capital requirements.",
      3000.0, True, "earnings_call", 0.92),
    r(E,"GS",
      "Stock mixed; higher NII benefit offset by investment banking slowdown fears.",
      "Begins marking down leveraged buyout financing pipeline.",
      "Q2 2022 (Jul 18): investment banking revenue -41% YoY; advisory revenue declines; trading strong.",
      -1300.0, True, "earnings_call", 0.90),
    r(E,"BAC",
      "Stock rises significantly; BAC most rate-sensitive of major US banks.",
      "Reprices loan and deposit products; NII guidance dramatically raised.",
      "Q2 2022 (Jul 18): raises 2022 NII guidance by $900M per quarter; NII up 22% YoY in Q2.",
      3600.0, True, "earnings_call", 0.92),
    r(E,"WMT",
      "No immediate operational response; stock had already declined on prior profit warning (May).",
      None,
      "Jul 26: issues profit warning — excess inventory requires markdowns; Q2 FY2023 operating income -66% YoY; withdraws guidance.",
      -900.0, True, "8k", 0.90),
    r(E,"TGT",
      None,
      None,
      "Had already issued May 18 profit warning; Q2 2022 operating income -87% YoY; $1.6B excess inventory markdown.",
      -1600.0, True, "earnings_call", 0.90),
    r(E,"COST",
      None,
      None,
      "Q4 FY2022 (Sep 22): revenue grew; inflation-driven average transaction size increases; maintained guidance.",
      500.0, False, "earnings_call", 0.78),
    r(E,"XOM",
      None,
      None,
      "Q2 2022: net income $17.9B — record quarterly profit driven by high oil prices; no material rate sensitivity.",
      17900.0, True, "earnings_call", 0.92),
    r(E,"CVX",
      None,
      None,
      "Q2 2022: net income $11.6B — record quarterly profit; no material rate sensitivity.",
      11600.0, True, "earnings_call", 0.92),
    r(E,"F",
      None,
      None,
      "Q2 2022: Rivian stake losses; commodity inflation and supply chain costs; adjusted EBIT below guidance.",
      -1200.0, True, "earnings_call", 0.82),
    r(E,"GM",
      None,
      None,
      "Q2 2022: maintained full-year guidance; strong vehicle pricing offsets some inflationary pressures.",
      400.0, False, "earnings_call", 0.78),
    r(E,"DAL",
      None,
      None,
      "Q2 2022 (Jul 13): raises revenue and EPS guidance; summer leisure demand strong despite recession fears; fuel cost partially offset.",
      200.0, True, "earnings_call", 0.80),
    r(E,"UAL",
      None,
      None,
      "Q2 2022 (Jul 20): profitable quarter; raises 2022 guidance; strong demand partially offsets higher fuel costs.",
      100.0, True, "earnings_call", 0.75),
    r(E,"JNJ",
      None,
      None,
      "Jul 19: raises 2022 EPS guidance despite FX headwinds; pharmaceutical segment strong; defensive business model insulated.",
      -100.0, True, "earnings_call", 0.82),
    r(E,"DIS",
      None,
      None,
      "Q3 FY2022 (Aug 10): Parks operating income $2.3B (record); Disney+ subs beat estimates; rate impact minimal on near-term results.",
      500.0, True, "earnings_call", 0.78),
]

# ============================================================
# EVENT 9: 2022_12_china_reopening
# ============================================================
E = "2022_12_china_reopening"
records += [
    r(E,"AAPL",
      "Stock rallies ~3% as Zero-COVID reversal signals Foxconn Zhengzhou recovery.",
      "Foxconn Zhengzhou (world's largest iPhone factory) begins full production ramp-up.",
      "Q1 FY2023 (Feb 2): revenue $117.2B beats estimates; iPhone supply chain normalized; China revenue $23.9B (+8% YoY).",
      3000.0, True, "earnings_call", 0.88),
    r(E,"MSFT",
      None,
      None,
      "Modest supply chain improvement for Surface devices; minimal direct China revenue impact.",
      None, False, "earnings_call", 0.72),
    r(E,"AMZN",
      None,
      None,
      "Consumer goods supply chain from China improves; inventory levels normalize; modest benefit to product availability.",
      500.0, False, "earnings_call", 0.70),
    r(E,"TSLA",
      "Shanghai Gigafactory begins full production ramp; stock rallies on reopening.",
      "Shanghai factory ramps to full capacity; Jan 2023: cuts China prices 6–13% to stimulate demand.",
      "Q4 2022 (Jan 26): 405,000 deliveries (record); raises 2023 delivery target; China price cuts signal demand strategy.",
      2000.0, False, "earnings_call", 0.88),
    null_r(E,"GOOGL", 0.75),
    null_r(E,"NFLX", 0.78),
    r(E,"JPM",
      "Raises China GDP growth forecast; China equity markets rally sharply.",
      "Resumes normal Beijing operations; expresses optimism on China deal flow recovery.",
      "2023 China investment banking activity recovers; incremental revenues estimated $200M.",
      200.0, False, "earnings_call", 0.72),
    r(E,"GS",
      "Raises China growth forecast to 5.5%.",
      "Resumes China deal activity; announces $200M commitment to China private equity.",
      "China banking fee recovery in 2023; estimated $300M incremental.",
      300.0, False, "earnings_call", 0.72),
    r(E,"BAC",
      "Raises China GDP forecast.",
      None,
      "Positive sentiment on China trade finance recovery; minimal direct revenue impact.",
      None, False, "earnings_call", 0.70),
    r(E,"WMT",
      None,
      None,
      "Supply chain normalization from China benefits in-stock rates; Q4 FY2023 inventory levels begin normalizing.",
      500.0, False, "earnings_call", 0.75),
    r(E,"TGT",
      None,
      None,
      "Supply chain improvement helps inventory normalization effort.",
      400.0, False, "earnings_call", 0.72),
    r(E,"COST",
      None,
      None,
      "Supply chain improvement; more predictable inventory flows from China suppliers.",
      200.0, False, "earnings_call", 0.70),
    r(E,"XOM",
      "Oil price rally on China demand recovery expectations.",
      "Raises China oil demand growth forecast.",
      "Oil price support from China demand recovery contributes to Q1 2023 results.",
      2000.0, False, "earnings_call", 0.75),
    r(E,"CVX",
      "Oil price support from China demand recovery.",
      None,
      "China demand recovery contributes to oil price support in Q1 2023.",
      1500.0, False, "earnings_call", 0.72),
    r(E,"F",
      None,
      None,
      "Supply chain improvement for Asian-sourced components; modest benefit.",
      300.0, False, "earnings_call", 0.68),
    r(E,"GM",
      "Stock rallies on China auto market recovery expectations.",
      "China joint ventures resume normal operations; raises China sales guidance.",
      "China JV equity income recovers; contributes ~$600M incremental vs depressed 2022 levels.",
      600.0, False, "earnings_call", 0.82),
    r(E,"DAL",
      None,
      None,
      "Jan 2023: announces resumption of US-China routes for spring 2023; incremental revenue opportunity.",
      100.0, False, "press_release", 0.78),
    r(E,"UAL",
      None,
      "Jan 2023: announces resumption of San Francisco–Shanghai route beginning March 2023.",
      "China route revenue gradually recovers through 2023.",
      100.0, False, "press_release", 0.75),
    r(E,"JNJ",
      None,
      None,
      "China pharmaceutical and medical device sales recovery; China segment revenues rebound.",
      300.0, False, "earnings_call", 0.75),
    r(E,"DIS",
      None,
      "Shanghai Disneyland increases capacity; resumes normal operations.",
      "Shanghai Disneyland attendance and per-cap spending recovers through Q1 2023.",
      200.0, False, "earnings_call", 0.78),
]

# ============================================================
# EVENT 10: 2023_03_svb_collapse
# ============================================================
E = "2023_03_svb_collapse"
records += [
    null_r(E,"AAPL", 0.85),
    r(E,"MSFT",
      None,
      "Offers payment flexibility for startup customers who had funds frozen at SVB; Azure continues normal operations.",
      "Immaterial financial impact; some startup ecosystem disruption but large-cap customers unaffected.",
      None, False, "press_release", 0.78),
    r(E,"AMZN",
      None,
      "AWS announces expanded startup support programs for companies affected by SVB.",
      "No material financial impact; AWS continues normal operations.",
      None, False, "press_release", 0.75),
    null_r(E,"TSLA", 0.85),
    null_r(E,"GOOGL", 0.82),
    null_r(E,"NFLX", 0.82),
    r(E,"JPM",
      "Sees significant deposit inflows as flight-to-quality accelerates.",
      "Markets JPM's balance sheet strength; deposit inflows from regional bank customers.",
      "May 1: acquires First Republic Bank from FDIC for $10.6B; acquires $173B in loans and $30B in securities at discount.",
      2900.0, True, "8k", 0.92),
    r(E,"GS",
      "Managed SVB's $21B bond portfolio sale (announced Mar 8) that triggered the bank run; reputational scrutiny.",
      "Shares decline ~5% as reputational concerns mount; no direct financial loss from SVB relationship.",
      "Estimated -$200M from reputational/deal-flow impact and increased scrutiny.",
      -200.0, False, "earnings_call", 0.80),
    r(E,"BAC",
      "Sees initial deposit inflows as flight-to-quality; stock also declines on contagion fears.",
      "Stock falls ~7% on contagion fears; analysts cite higher unrealized bond losses (~$100B+) in held-to-maturity portfolio.",
      "Net deposit flows positive short-term; longer-term some deposits migrate to money market funds chasing higher yields.",
      None, False, "earnings_call", 0.78),
    null_r(E,"WMT", 0.88),
    null_r(E,"TGT", 0.88),
    null_r(E,"COST", 0.88),
    null_r(E,"XOM", 0.88),
    null_r(E,"CVX", 0.88),
    null_r(E,"F", 0.85),
    null_r(E,"GM", 0.85),
    null_r(E,"DAL", 0.85),
    null_r(E,"UAL", 0.85),
    null_r(E,"JNJ", 0.85),
    null_r(E,"DIS", 0.85),
]

assert len(records) == 200, f"Expected 200 records, got {len(records)}"

with open(OUT, "w") as fp:
    for rec in records:
        fp.write(json.dumps(rec) + "\n")

print(f"Wrote {len(records)} records to {OUT}")
